stages:
  - lint
  - package
  - upload

lint:
  image:
    name: alpine/helm:3.6.3
    entrypoint: ["/bin/sh", "-c"]
  stage: lint
  script:
    - 'helm lint .'

package:
  image:
    name: alpine/helm:3.6.3
    entrypoint: ["/bin/sh", "-c"]
  stage: package
  script:
    - 'helm package -u -d build/ .'
  artifacts:
    paths:
      - build/

upload-beta:
  except:
    - main
  image: curlimages/curl:latest
  stage: upload
  script:
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@build/outline-0.0.8.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/beta/charts"'

upload-stable:
  only:
    - main
  image: curlimages/curl:latest
  stage: upload
  script:
    - 'curl --request POST --user gitlab-ci-token:$CI_JOB_TOKEN --form "chart=@build/outline-0.0.8.tgz" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/helm/api/stable/charts"'
